// Generated by gencpp from file calib/Action.msg
// DO NOT EDIT!


#ifndef CALIB_MESSAGE_ACTION_H
#define CALIB_MESSAGE_ACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace calib
{
template <class ContainerAllocator>
struct Action_
{
  typedef Action_<ContainerAllocator> Type;

  Action_()
    : target_tag(0)
    , dist(0.0)
    , angle(0.0)  {
    }
  Action_(const ContainerAllocator& _alloc)
    : target_tag(0)
    , dist(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _target_tag_type;
  _target_tag_type target_tag;

   typedef float _dist_type;
  _dist_type dist;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::calib::Action_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::calib::Action_<ContainerAllocator> const> ConstPtr;

}; // struct Action_

typedef ::calib::Action_<std::allocator<void> > Action;

typedef boost::shared_ptr< ::calib::Action > ActionPtr;
typedef boost::shared_ptr< ::calib::Action const> ActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::calib::Action_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::calib::Action_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace calib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'calib': ['/home/et/Documents/lfm_ws/src/calib/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::calib::Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calib::Action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calib::Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calib::Action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calib::Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calib::Action_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::calib::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7529da8ba0ed13c6f3938479d680da6a";
  }

  static const char* value(const ::calib::Action_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7529da8ba0ed13c6ULL;
  static const uint64_t static_value2 = 0xf3938479d680da6aULL;
};

template<class ContainerAllocator>
struct DataType< ::calib::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calib/Action";
  }

  static const char* value(const ::calib::Action_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::calib::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 target_tag\n\
float32 dist\n\
float32 angle\n\
";
  }

  static const char* value(const ::calib::Action_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::calib::Action_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_tag);
      stream.next(m.dist);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Action_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::calib::Action_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::calib::Action_<ContainerAllocator>& v)
  {
    s << indent << "target_tag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_tag);
    s << indent << "dist: ";
    Printer<float>::stream(s, indent + "  ", v.dist);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CALIB_MESSAGE_ACTION_H
