// Generated by gencpp from file calib/Links.msg
// DO NOT EDIT!


#ifndef CALIB_MESSAGE_LINKS_H
#define CALIB_MESSAGE_LINKS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace calib
{
template <class ContainerAllocator>
struct Links_
{
  typedef Links_<ContainerAllocator> Type;

  Links_()
    : link_id()
    , link_active_prob()  {
    }
  Links_(const ContainerAllocator& _alloc)
    : link_id(_alloc)
    , link_active_prob(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _link_id_type;
  _link_id_type link_id;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _link_active_prob_type;
  _link_active_prob_type link_active_prob;





  typedef boost::shared_ptr< ::calib::Links_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::calib::Links_<ContainerAllocator> const> ConstPtr;

}; // struct Links_

typedef ::calib::Links_<std::allocator<void> > Links;

typedef boost::shared_ptr< ::calib::Links > LinksPtr;
typedef boost::shared_ptr< ::calib::Links const> LinksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::calib::Links_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::calib::Links_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace calib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'calib': ['/home/et/Documents/lfm_ws/src/calib/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::calib::Links_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calib::Links_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calib::Links_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calib::Links_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calib::Links_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calib::Links_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::calib::Links_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20b3840007e10c6883a36f0694bd3f6b";
  }

  static const char* value(const ::calib::Links_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20b3840007e10c68ULL;
  static const uint64_t static_value2 = 0x83a36f0694bd3f6bULL;
};

template<class ContainerAllocator>
struct DataType< ::calib::Links_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calib/Links";
  }

  static const char* value(const ::calib::Links_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::calib::Links_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] link_id\n\
float32[] link_active_prob\n\
";
  }

  static const char* value(const ::calib::Links_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::calib::Links_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.link_id);
      stream.next(m.link_active_prob);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Links_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::calib::Links_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::calib::Links_<ContainerAllocator>& v)
  {
    s << indent << "link_id[]" << std::endl;
    for (size_t i = 0; i < v.link_id.size(); ++i)
    {
      s << indent << "  link_id[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.link_id[i]);
    }
    s << indent << "link_active_prob[]" << std::endl;
    for (size_t i = 0; i < v.link_active_prob.size(); ++i)
    {
      s << indent << "  link_active_prob[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.link_active_prob[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CALIB_MESSAGE_LINKS_H
